Update lite-update

diff --git a/lite-update b/lite-update
--- a/lite-update
+++ b/lite-update
@@ -6,7 +6,7 @@ LOGFILE=/var/log/lite-update.log
 
 function log(){
     message="$@"
-    echo '['$(date +%D\ %H:%M:%S)'] '$message >>$LOGFILE
+    echo '['$(date +%D\ %H:%M:%S)'] '$message | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})*)?m//g" >>$LOGFILE
 }
 
 function checklock () {
@@ -82,18 +82,18 @@ function showlog () {
 }
 
 function about () {
-	zenity --info --title="$APPNAME About..." --height=300 --width=400 --text="$APPNAME is a small GUI based on zenity for Linux Lite, desinged for Linux Lite and very easy to use.\n\nLicence GPL v2."
+	zenity --info --title="$APPNAME About..." --height=300 --width=400 --text="$APPNAME is a small GUI based on zenity for Linux Lite, desinged for Linux Lite and very easy to use.\n\nLicence GPL v2.\n\n Milos Pavlovic 2015"
 	main
 }
 
 function help () {
-	zenity --text-info --title="$APPNAME Help" --height=600 --width=800 --html --filename="/usr/share/doc/litemanual/index.html"
+	zenity --text-info --title="$APPNAME Help" --height=600 --width=800 --text="/usr/share/doc/litemanual/index.html"
 	main
 }
 
 function update() {
 
-# Temporary file for error tracking 
+# Temporary file for error tracking
 TMPLIST=$(mktemp /tmp/repos.XXXXXX)
 
   APTUPDATE=$(grep '^deb' -c /etc/apt/sources.list) # Total of repositories registered, this is approximated
@@ -108,7 +108,7 @@ TMPLIST=$(mktemp /tmp/repos.XXXXXX)
 					rm -f $TMPLIST
 					unset TMPLIST
                                         zenity --error \
-                                        --title="Error" --text="$APPNAME couldn't fetch the package cache information lists."
+                                        --title="Error" --text="$APPNAME couldn't fetch the package cache information lists.\nCheck the log for details"
 
                                        main
                                 fi
@@ -122,7 +122,8 @@ unset TMPLIST
 UPDATES=$(mktemp /tmp/updateslist.XXXXXX)
 
 # Creates a list in /tmp/updateslist
-apt-get --just-print upgrade 2>&1 | perl -ne 'if (/Inst\s([\w,\-,\d,\.,~,:,\+]+)\s\[([\w,\-,\d,\.,~,:,\+]+)\]\s\(([\w,\-,\d,\.,~,:,\+]+)\)? /i) {print "Name: $1 INSTALLED: $2 AVAILABLE: $3\n"}' | awk '{print NR,":\t"$0}' | tee $UPDATES >/dev/null
+apt-get --just-print upgrade 2>&1 | perl -ne 'if (/Inst\s([\w,\-,\d,\.,~,:,\+]+)\s\[([\w,\-,\d,\.,~,:,\+]+)\]\s\(([\w,\-,\d,\.,~,:,\+]+)\)? /i) {print "$1 $2 $3\n"}' \
+| awk '{printf("%02d %s\n", NR, $0)}' | sed 's/^/TRUE /g;s/[ ]/\n/g' | tee $UPDATES  | zenity --progress --pulsate --title="Calculating Updates" --text="Please wait..." --auto-close
 
 # Check if any updates are available, if there are none, script pops up dialog box saying 'No Updates Available', removes /tmp/updateslist.XXXXXX
 if [  -z "$(cat $UPDATES)"  ]; then
@@ -135,25 +136,28 @@ if [  -z "$(cat $UPDATES)"  ]; then
    main
 fi
 	# Log available updates
-    lst_upgrades=$(awk '/Name:/{print $4"\n"}' $UPDATES)
-    log "INFO: Updates available: $lst_upgrades"
 
-# Insert text into  /tmp/updateslist.XXXXXX
-sed -i -e '1 i\List of available Updates' -e '1 i\Click Update to continue or Cancel to stop the update process\n'  $UPDATES
+	 ct=5
+    lst_upgrades=$(awk -v patt="$ct" 'NR % patt == 3' $UPDATES) # Prints every 5th line starting from the 3rd in $UPDATES
+    log "INFO: Updates available: $lst_upgrades"
+	unset ct
 
 # Erase existing available info
 sudo dpkg --clear-avail
 
-
+#Read everything from /tmp/updateslist.XXXXXX to array a
+readarray -t a < $UPDATES
 
 # Call the zenity dialog to show update list
-zenity --text-info --ok-label="Update" --cancel-label="Cancel" --title="$APPNAME" --width=780 --height=300 --filename="$UPDATES"
-      if [ "$?" -eq "0" ];then
+UPD_LIST=$(zenity --list --print-column=3 --checklist --separator=" " --text="List of available Updates\nClick Update to continue or Cancel to stop the update process" \
+--width=800 --height=700 --ok-label="Update"  --column="Pick" --column="Num" --column="Name" --column="Installed" --column="Available" "${a[@]}" )
 
       # Continue script if no halt
+      if [ "$?" -eq "0" ];then
+
 
 	# Write log
-    lst_upgrades=$(awk '/Name:/{print $4}' $UPDATES)
+    lst_upgrades=$(echo $UPD_LIST)
     log "INFO: Updating: $lst_upgrades"
 
                  # Remove tmp file and unset variable
@@ -161,14 +165,14 @@ zenity --text-info --ok-label="Update" --cancel-label="Cancel" --title="$APPNAME
                  unset UPDATES
 
 	# Begin upgrade
-	sudo DEBIAN_FRONTEND=noninteractive apt-get  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade -y  2>&1 | tee /var/log/llupdates.log | awk ' BEGIN { FS=" "; total=1;end_download=0} /upgraded/ {total= $1 + $3;FS="[ :]" } /^Get:[[:digit:]]+/ {printf "#Downloading %s %s %s\n",$6,$(NF-1),$NF;print int(($2 - 1) * 100 / total); fflush(stdout)} /^\(Reading / {if (end_download==0){print 100;fflush(stdout);end_download=1}} /^(Preparing|Unpacking|Selecting|Processing|Setting|Download)/ {print "#", substr($0, 0, 128); fflush(stdout)}' \
-	 | ( zenity --progress --width=600 --text="Downloading package(s)...\nThis may take a while." --title="Downloading - please wait..." --percentage=0 --auto-close ; zenity --progress --width=600 --text="Installing and configuring packages...\nThis may take a while." --title="Installing - please wait..."  --pulsate --auto-close )
+	sudo DEBIAN_FRONTEND=noninteractive apt-get  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install --show-progress $UPD_LIST -y  2>&1 | tee /var/log/llupdates.log | awk ' BEGIN { FS=" "; total=1;end_download=0} /upgraded/ {total= $1 + $3;FS="[ :]" } /^Get:[[:digit:]]+/ {printf "#Downloading %s %s %s\n",$6,$(NF-1),$NF;print int(($2 - 1) * 100 / total); fflush(stdout)} /^\(Reading / {if (end_download==0){print 100;fflush(stdout);end_download=1}} /^(Preparing|Unpacking|Selecting|Processing|Setting|Download)/ {print "#", $0; fflush(stdout)}  /^Progress/ {print  match($0, /([0-9]+)/, arr); if(arr[1] != "") print arr[1] ; fflush(stdout)}' \
+    | ( zenity --window-icon=$ic --progress --width=600 --text="Downloading package(s)...\nThis may take a while." --title="Downloading - please wait..." --percentage=0 --auto-close ; zenity --progress --window-icon=$ic --width=600 --text="Installing and configuring packages...\nThis may take a while." --title="Installing - please wait..." --auto-close )
 
                                 if [ "${PIPESTATUS[0]}" -ne "0" ]; then
 					err_msg=$(awk '/^(W:|E:)/{$1=""; print $0}' /var/log/llupdates.log | tail -n 1)
 					log "ERROR:$err_msg"
                                         zenity --error \
-                                        --title="Error" --text="Updates have failed."
+                                        --title="Error" --text="Updates have failed.\nCheck the log for details."
                                         main
                                 fi
 
@@ -177,7 +181,6 @@ zenity --text-info --ok-label="Update" --cancel-label="Cancel" --title="$APPNAME
        log "INFO: User has canceled software upgrades."
          rm -f $UPDATES
         unset UPDATES
-	 zenity --error --title="$APPNAME"  --text="Updates Cancelled."
          main
     fi
 
